### PR TITLE
Feature/setup of the JS Documentation

### PR DESCRIPTION
**Pull request by solonkonora**
done designing the desktop view of the page

### CODE REVIEW

**Comment by nganifaith** [comment]
@solonkonora great job. However, your text isn't properly align.

**Review by nganifaith — CHANGES_REQUESTED** [review]
Great attempt @solonkonora 
your content however is overlapping. Refer to screenshot below

**Review by nganifaith — CHANGES_REQUESTED** [review]
great job @solonkonora. 

- [ ] work on the changes that was mentioned in the previous review.
- [ ] look at image below
Screenshot 2023-11-18 at 20 55 19

fix content

**Comment by solonkonora** [comment]
Madam this page was not made responsive ohh, this view you sent now, i dont
see on my laptop like this, i have been checking since that what is the
problem .

**Pull request merged**
